using System.Text;

namespace Broiler.Code.Phase0.Prototype.Fixtures;

/// <summary>
/// Deterministic, generated-in-memory source fixtures. Large blobs are not
/// checked in — the same rule the Formatting Codes Phase 0 harness follows —
/// so the reviewable artifact is this generator plus the recorded counts.
/// </summary>
public static class SourceFixtures
{
    /// <summary>
    /// Builds a C# file with <paramref name="lineCount"/> lines whose content
    /// exercises every branch of the portable classifier: line and block
    /// comments, documentation comments, regular, verbatim, interpolated and
    /// raw strings, character and numeric literals, directives, operators, and
    /// keywords.
    /// </summary>
    /// <param name="minimumLineWidth">
    /// Pads every line to at least this many characters with trailing spaces.
    /// Padding is whitespace on purpose: the lexer emits no span for it, so the
    /// wide variant changes only the byte size and the line length, leaving the
    /// span count and code density identical to the natural variant. That
    /// isolates "cost of a large document" from "cost of dense code", and it is
    /// how the 10 MiB Phase 1 fixture is reached at 100,000 lines without
    /// pretending real code averages 104 columns.
    /// </param>
    public static string BuildCSharpFile(int lineCount, int seed = 0, int minimumLineWidth = 0)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(lineCount, 1);

        var builder = new StringBuilder(lineCount * Math.Max(96, minimumLineWidth + 8));
        int line = 0;
        int method = 0;
        var state = new GeneratorState(builder, lineCount, minimumLineWidth);

        Append(ref state, ref line, "// <auto-generated />");
        Append(ref state, ref line, "#nullable enable");
        Append(ref state, ref line, "using System;");
        Append(ref state, ref line, "using System.Collections.Generic;");
        Append(ref state, ref line, string.Empty);
        Append(ref state, ref line, $"namespace Generated.Fixture{seed};");
        Append(ref state, ref line, string.Empty);

        while (line < lineCount)
        {
            int id = method++;
            AppendBlock(ref state, ref line, id, seed);
        }

        return builder.ToString();
    }

    /// <summary>
    /// A solution-shaped fixture: <paramref name="fileCount"/> files of
    /// <paramref name="linesPerFile"/> lines each. Used for the 1,000-file
    /// measurement, where per-file overhead matters more than per-line cost.
    /// </summary>
    public static string[] BuildSolution(int fileCount, int linesPerFile, int minimumLineWidth = 0)
    {
        var files = new string[fileCount];
        for (int i = 0; i < fileCount; i++)
            files[i] = BuildCSharpFile(linesPerFile, i, minimumLineWidth);
        return files;
    }

    /// <summary>
    /// Sources that are wrong to classify line-by-line unless multi-line state
    /// is carried correctly. Every one of them is checked for
    /// incremental/full agreement after each edit in the trace runner.
    /// </summary>
    public static (string Name, string Text)[] MultiLineStateSources() =>
    [
        ("block-comment", "var a = 1;\n/* opened\nstill inside\n*/ var b = 2;\n"),
        ("doc-block-comment", "/** doc\n * more\n */\nclass C { }\n"),
        ("verbatim-string", "var p = @\"C:\\one\ntwo\"\"three\n\";\nvar q = 3;\n"),
        ("interpolated-verbatim", "var p = $@\"a{{b}}\nnext {x}\n\";\nvar q = 3;\n"),
        ("raw-string", "var r = \"\"\"\nline one \"not closed\"\n\"\"\";\nvar s = 4;\n"),
        ("raw-string-interpolated", "var r = $$\"\"\"\n{{{value}}} and {{literal}}\n\"\"\";\n"),
        ("unterminated-string", "var s = \"open\nvar t = 2;\n"),
        ("directive", "#if DEBUG\nConsole.WriteLine(\"d\");\n#endif\n"),
        ("crlf-mixed", "var a = 1;\r\n/* c\r\nd */\r\nvar b = 2;\n"),
        ("empty", string.Empty),
        ("no-trailing-newline", "var a = 1;"),
    ];

    private ref struct GeneratorState(StringBuilder builder, int limit, int minimumLineWidth)
    {
        public readonly StringBuilder Builder = builder;
        public readonly int Limit = limit;
        public readonly int MinimumLineWidth = minimumLineWidth;
    }

    private static void AppendBlock(ref GeneratorState state, ref int line, int id, int seed)
    {
        int flavor = (id + seed) % 6;

        Append(ref state, ref line, "/// <summary>");
        Append(ref state, ref line, $"/// Generated member {id}.");
        Append(ref state, ref line, "/// </summary>");
        Append(ref state, ref line, $"public sealed class Widget{id}");
        Append(ref state, ref line, "{");
        Append(ref state, ref line, $"    private const int Limit = 0x{id:X4};");
        Append(ref state, ref line, $"    private readonly double _scale = {id % 97}.{id % 13}e2;");
        Append(ref state, ref line, "    private char _marker = '\\u00e9';");
        Append(ref state, ref line, string.Empty);
        Append(ref state, ref line, "    public int Measure(IReadOnlyList<string> values)");
        Append(ref state, ref line, "    {");
        Append(ref state, ref line, "        int total = 0;");
        Append(ref state, ref line, "        foreach (var value in values)");
        Append(ref state, ref line, "        {");
        Append(ref state, ref line, "            if (value.Length > Limit && total < 1_000_000)");
        Append(ref state, ref line, "                total += value.Length * 3 - 1;");
        Append(ref state, ref line, "            else");
        Append(ref state, ref line, "                total = checked(total / 2);");
        Append(ref state, ref line, "        }");
        Append(ref state, ref line, string.Empty);

        switch (flavor)
        {
            case 0:
                Append(ref state, ref line, "        // A plain trailing comment.");
                Append(ref state, ref line, "        return total;");
                break;
            case 1:
                Append(ref state, ref line, "        /* a block comment");
                Append(ref state, ref line, "           spanning three");
                Append(ref state, ref line, "           source lines */");
                Append(ref state, ref line, "        return total;");
                break;
            case 2:
                Append(ref state, ref line, "        var path = @\"C:\\generated\\path\";");
                Append(ref state, ref line, "        return total + path.Length;");
                break;
            case 3:
                Append(ref state, ref line, "        var text = $\"total={total} scale={_scale:F2}\";");
                Append(ref state, ref line, "        return total + text.Length;");
                break;
            case 4:
                Append(ref state, ref line, "        var raw = \"\"\"");
                Append(ref state, ref line, "            a \"quoted\" fragment");
                Append(ref state, ref line, "            \"\"\";");
                Append(ref state, ref line, "        return total + raw.Length;");
                break;
            default:
                Append(ref state, ref line, "#if DEBUG");
                Append(ref state, ref line, "        Console.WriteLine(\"debug\");");
                Append(ref state, ref line, "#endif");
                Append(ref state, ref line, "        return total;");
                break;
        }

        Append(ref state, ref line, "    }");
        Append(ref state, ref line, "}");
        Append(ref state, ref line, string.Empty);
    }

    private static void Append(ref GeneratorState state, ref int line, string text)
    {
        if (line >= state.Limit)
            return;
        state.Builder.Append(text);
        if (text.Length < state.MinimumLineWidth)
            state.Builder.Append(' ', state.MinimumLineWidth - text.Length);
        state.Builder.Append('\n');
        line++;
    }
}
